//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibHutech_DoAnLapTrinhWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.LichSus = new HashSet<LichSu>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string ImgSach { get; set; }
        public string DuongDan { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> MaMon { get; set; }
        public string NoiDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSu> LichSus { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
